/* =========================================================
   syllabus-data.js — all syllabus content (data-driven)
   GS I–IV and Anthropology I & II are reproduced verbatim
   from the official CSE syllabus PDF provided.
   ========================================================= */

const SYLLABUS = {
  /* ---------------- PRELIMINARY ---------------- */
  prelims: {
    title: "Preliminary Stage",
    sub: "Two compulsory papers · 200 marks each",
    cards: [
      {
        id: "pre-gs1",
        title: "General Studies Paper I",
        meta: "200 Marks · Duration: Two hours",
        sections: [
          { items: [
            "Current events of national and international importance.",
            "History of India and Indian National Movement.",
            "Indian and World Geography — Physical, Social, Economic Geography of India and the World.",
            "Indian Polity and Governance — Constitution, Political System, Panchayati Raj, Public Policy, Rights Issues, etc.",
            "Economic and Social Development — Sustainable Development, Poverty, Inclusion, Demographics, Social Sector initiatives, etc.",
            "General issues on Environmental Ecology, Bio-diversity and Climate Change — that do not require subject specialization.",
            "General Science.",
          ]},
        ],
      },
      {
        id: "pre-gs2",
        title: "General Studies Paper II (CSAT)",
        meta: "200 Marks · Duration: Two hours · Qualifying (33%)",
        sections: [
          { items: [
            "Comprehension.",
            "Interpersonal skills including communication skills.",
            "Logical reasoning and analytical ability.",
            "Decision-making and problem-solving.",
            "General mental ability.",
            "Basic numeracy (numbers and their relations, orders of magnitude, etc.) (Class X level); Data interpretation (charts, graphs, tables, data sufficiency etc. — Class X level).",
            "English Language Comprehension skills (Class X level).",
          ]},
          { note: "Note: Questions relating to English Language Comprehension skills of Class X level will be tested through passages from English language only, without Hindi translation in the question paper. Questions are multiple choice, objective type." },
        ],
      },
    ],
  },

  /* ---------------- MAINS ---------------- */
  mains: {
    title: "Mains Stage",
    sub: "Essay · GS I–IV · Languages · Optional (Anthropology)",
    cards: [
      {
        id: "essay",
        title: "Essay",
        meta: "Paper I · 250 Marks",
        blank: true,
      },
      {
        id: "english",
        title: "English Language",
        meta: "Qualifying Paper · 10th standard level",
        sections: [
          { items: [
            "Comprehension of Given Passages",
            "Precis Writing",
            "Usage and Vocabulary",
            "Short Essay",
          ]},
        ],
      },
      {
        id: "hindi",
        title: "Hindi Language",
        meta: "Qualifying Paper · 10th standard level",
        sections: [
          { items: [
            "Comprehension of Given Passages",
            "Precis Writing",
            "Usage and Vocabulary",
            "Short Essay",
          ]},
        ],
      },
      {
        id: "gs1",
        title: "GS Paper I",
        meta: "Indian Heritage and Culture, History and Geography of the World and Society",
        sections: [
          { items: [
            "Indian culture will cover the salient aspects of Art Forms, Literature and Architecture from ancient to modern times.",
            "Modern Indian history from about the middle of the eighteenth century until the present — significant events, personalities, issues.",
            "The Freedom Struggle — its various stages and important contributors / contributions from different parts of the country.",
            "Post-independence consolidation and reorganization within the country.",
            "History of the world will include events from 18th century such as industrial revolution, world wars, redrawal of national boundaries, colonization, decolonization, political philosophies like communism, capitalism, socialism etc. — their forms and effect on the society.",
            "Salient features of Indian Society, Diversity of India.",
            "Role of women and women's organization, population and associated issues, poverty and developmental issues, urbanization, their problems and their remedies.",
            "Effects of globalization on Indian society.",
            "Social empowerment, communalism, regionalism & secularism.",
            "Salient features of world's physical geography.",
            "Distribution of key natural resources across the world (including South Asia and the Indian sub-continent); factors responsible for the location of primary, secondary, and tertiary sector industries in various parts of the world (including India).",
            "Important Geophysical phenomena such as earthquakes, Tsunami, Volcanic activity, cyclone etc., geographical features and their location — changes in critical geographical features (including water-bodies and ice-caps) and in flora and fauna and the effects of such changes.",
          ]},
        ],
      },
      {
        id: "gs2",
        title: "GS Paper II",
        meta: "Governance, Constitution, Polity, Social Justice and International Relations",
        sections: [
          { items: [
            "Indian Constitution — historical underpinnings, evolution, features, amendments, significant provisions and basic structure.",
            "Functions and responsibilities of the Union and the States, issues and challenges pertaining to the federal structure, devolution of powers and finances up to local levels and challenges therein.",
            "Separation of powers between various organs, dispute redressal mechanisms and institutions.",
            "Comparison of the Indian constitutional scheme with that of other countries.",
            "Parliament and State Legislatures — structure, functioning, conduct of business, powers & privileges and issues arising out of these.",
            "Structure, organization and functioning of the Executive and the Judiciary; Ministries and Departments of the Government; pressure groups and formal/informal associations and their role in the Polity.",
            "Salient features of the Representation of People's Act.",
            "Appointment to various Constitutional posts, powers, functions and responsibilities of various Constitutional Bodies.",
            "Statutory, regulatory and various quasi-judicial bodies.",
            "Government policies and interventions for development in various sectors and issues arising out of their design and implementation.",
            "Development processes and the development industry — the role of NGOs, SHGs, various groups and associations, donors, charities, institutional and other stakeholders.",
            "Welfare schemes for vulnerable sections of the population by the Centre and States and the performance of these schemes; mechanisms, laws, institutions and Bodies constituted for the protection and betterment of these vulnerable sections.",
            "Issues relating to development and management of Social Sector/Services relating to Health, Education, Human Resources.",
            "Issues relating to poverty and hunger.",
            "Important aspects of governance, transparency and accountability, e-governance — applications, models, successes, limitations, and potential; citizens charters, transparency & accountability and institutional and other measures.",
            "Role of civil services in a democracy.",
            "India and its neighborhood — relations.",
            "Bilateral, regional and global groupings and agreements involving India and/or affecting India's interests.",
            "Effect of policies and politics of developed and developing countries on India's interests, Indian diaspora.",
            "Important International institutions, agencies and fora — their structure, mandate.",
          ]},
        ],
      },
      {
        id: "gs3",
        title: "GS Paper III",
        meta: "Technology, Economic Development, Bio-diversity, Environment, Security and Disaster Management",
        sections: [
          { items: [
            "Indian Economy and issues relating to planning, mobilization of resources, growth, development and employment.",
            "Inclusive growth and issues arising from it.",
            "Government Budgeting.",
            "Major crops — cropping patterns in various parts of the country, different types of irrigation and irrigation systems; storage, transport and marketing of agricultural produce and issues and related constraints; e-technology in the aid of farmers.",
            "Issues related to direct and indirect farm subsidies and minimum support prices; Public Distribution System — objectives, functioning, limitations, revamping; issues of buffer stocks and food security; Technology missions; economics of animal-rearing.",
            "Food processing and related industries in India — scope and significance, location, upstream and downstream requirements, supply chain management.",
            "Land reforms in India.",
            "Effects of liberalization on the economy, changes in industrial policy and their effects on industrial growth.",
            "Infrastructure: Energy, Ports, Roads, Airports, Railways etc.",
            "Investment models.",
            "Science and Technology — developments and their applications and effects in everyday life.",
            "Achievements of Indians in science & technology; indigenization of technology and developing new technology.",
            "Awareness in the fields of IT, Space, Computers, robotics, nano-technology, bio-technology and issues relating to intellectual property rights.",
            "Conservation, environmental pollution and degradation, environmental impact assessment.",
            "Disaster and disaster management.",
            "Linkages between development and spread of extremism.",
            "Role of external state and non-state actors in creating challenges to internal security.",
            "Challenges to internal security through communication networks, role of media and social networking sites in internal security challenges, basics of cyber security; money-laundering and its prevention.",
            "Security challenges and their management in border areas; linkages of organized crime with terrorism.",
            "Various Security forces and agencies and their mandate.",
          ]},
        ],
      },
      {
        id: "gs4",
        title: "GS Paper IV",
        meta: "Ethics, Integrity, and Aptitude",
        sections: [
          { note: "This paper will include questions to test the candidates' attitude and approach to issues relating to integrity, probity in public life and their problem-solving approach to various issues and conflicts faced in dealing with society. Questions may utilise the case study approach to determine these aspects. The following broad areas will be covered:" },
          { items: [
            "Ethics and Human Interface: Essence, determinants and consequences of Ethics in human actions; dimensions of ethics; ethics in private and public relationships. Human Values — lessons from the lives and teachings of great leaders, reformers and administrators; role of family, society and educational institutions in inculcating values.",
            "Attitude: content, structure, function; its influence and relation with thought and behaviour; moral and political attitudes; social influence and persuasion.",
            "Aptitude and foundational values for Civil Service — integrity, impartiality and non-partisanship, objectivity, dedication to public service, empathy, tolerance and compassion towards the weaker sections.",
            "Emotional intelligence — concepts, and their utilities and application in administration and governance.",
            "Contributions of moral thinkers and philosophers from India and world.",
            "Public/Civil service values and Ethics in Public administration: Status and problems; ethical concerns and dilemmas in government and private institutions; laws, rules, regulations and conscience as sources of ethical guidance; accountability and ethical governance; strengthening of ethical and moral values in governance; ethical issues in international relations and funding; corporate governance.",
            "Probity in Governance: Concept of public service; Philosophical basis of governance and probity; Information sharing and transparency in government, Right to Information, Codes of Ethics, Codes of Conduct, Citizen's Charters, Work culture, Quality of service delivery, Utilization of public funds, challenges of corruption.",
            "Case Studies on above issues.",
          ]},
        ],
      },
      {
        id: "anthro1",
        title: "Anthropology Paper I",
        meta: "Optional Subject · Paper VI",
        sections: [
          { items: [
            "1.1 Meaning, scope and development of Anthropology.",
            "1.2 Relationships with other disciplines: Social Sciences, Behavioural Sciences, Life Sciences, Medical Sciences, Earth Sciences and Humanities.",
            "1.3 Main branches of Anthropology, their scope and relevance: (a) Social-cultural Anthropology; (b) Biological Anthropology; (c) Archaeological Anthropology; (d) Linguistic Anthropology.",
            "1.4 Human Evolution and emergence of Man: (a) Biological and Cultural factors in human evolution; (b) Theories of Organic Evolution (Pre-Darwinian, Darwinian and Post-Darwinian); (c) Synthetic theory of evolution; Brief outline of terms and concepts of evolutionary biology (Doll's rule, Cope's rule, Gause's rule, parallelism, convergence, adaptive radiation, and mosaic evolution).",
            "1.5 Characteristics of Primates; Evolutionary Trend and Primate Taxonomy; Primate Adaptations (Arboreal and Terrestrial); Primate Taxonomy; Primate Behaviour; Tertiary and Quaternary fossil primates; Living Major Primates; Comparative Anatomy of Man and Apes; Skeletal changes due to erect posture and its implications.",
            "1.6 Phylogenetic status, characteristics and geographical distribution of the following: (a) Plio-pleistocene hominids in South and East Africa — Australopithecines; (b) Homo erectus: Africa (Paranthropus), Europe (Homo erectus heidelbergensis), Asia (Homo erectus javanicus, Homo erectus pekinensis); (c) Neanderthal Man — La-Chapelle-aux-saints (Classical type), Mt. Carmel (Progressive type); (d) Rhodesian man; (e) Homo sapiens — Cromagnon, Grimaldi and Chancelede.",
            "1.7 The biological basis of life: The Cell, DNA structure and replication, Protein Synthesis, Gene, Mutation, Chromosomes, and Cell Division.",
            "1.8 (a) Principles of Prehistoric Archaeology. Chronology: Relative and Absolute Dating methods. (b) Cultural Evolution — Broad Outlines of Prehistoric cultures: (i) Paleolithic; (ii) Mesolithic; (iii) Neolithic; (iv) Chalcolithic; (v) Copper-Bronze Age; (vi) Iron Age.",
            "2.1 The Nature of Culture: The concept and characteristics of culture and civilization; Ethnocentrism vis-à-vis cultural Relativism.",
            "2.2 The Nature of Society: Concept of Society; Society and Culture; Social Institutions; Social groups; and Social stratification.",
            "2.3 Marriage: Definition and universality; Laws of marriage (endogamy, exogamy, hypergamy, hypogamy, incest taboo); Types of marriage (monogamy, polygamy, polyandry, group marriage); Functions of marriage; Marriage regulations (preferential, prescriptive and proscriptive); Marriage payments (bride wealth and dowry).",
            "2.4 Family: Definition and universality; Family, household and domestic groups; functions of family; Types of family (from the perspectives of structure, blood relation, marriage, residence and succession); Impact of urbanization, industrialization and feminist movements on family.",
            "2.5 Kinship: Consanguinity and Affinity; Principles and types of descent (Unilineal, Double, Bilateral, Ambilineal); Forms of descent groups (lineage, clan, phratry, moiety and kindred); Kinship terminology (descriptive and classificatory); Descent, Filiation and Complimentary Filiation; Descent and Alliance.",
            "3. Economic organization: Meaning, scope and relevance of economic anthropology; Formalist and Substantivist debate; Principles governing production, distribution and exchange (reciprocity, redistribution and market), in communities subsisting on hunting and gathering, fishing, swiddening, pastoralism, horticulture, and agriculture; globalization and indigenous economic systems.",
            "4. Political organization and Social Control: Band, tribe, chiefdom, kingdom and state; concepts of power, authority and legitimacy; social control, law and justice in simple societies.",
            "5. Religion: Anthropological approaches to the study of religion (evolutionary, psychological and functional); monotheism and polytheism; sacred and profane; myths and rituals; forms of religion in tribal and peasant societies (animism, animatism, fetishism, naturism and totemism); religion, magic and science distinguished; magico-religious functionaries (priest, shaman, medicine man, sorcerer and witch).",
            "6. Anthropological theories: (a) Classical evolutionism (Tylor, Morgan and Frazer); (b) Historical particularism (Boas); Diffusionism (British, German and American); (c) Functionalism (Malinowski); Structural-functionalism (Radcliffe-Brown); (d) Structuralism (Lévi-Strauss and E. Leach); (e) Culture and personality (Benedict, Mead, Linton, Kardiner and Cora-du Bois); (f) Neo-evolutionism (Childe, White, Steward, Sahlins and Service); (g) Cultural materialism (Harris); (h) Symbolic and interpretive theories (Turner, Schneider and Geertz); (i) Cognitive theories (Tyler, Conklin); (j) Post-modernism in anthropology.",
            "7. Culture, language and communication: Nature, origin and characteristics of language; verbal and non-verbal communication; social context of language use.",
            "8. Research methods in anthropology: (a) Fieldwork tradition in anthropology; (b) Distinction between technique, method and methodology; (c) Tools of data collection: observation, interview, schedules, questionnaire, Case study, genealogy, life-history, oral history, secondary sources of information, participatory methods; (d) Analysis, interpretation and presentation of data.",
            "9.1 Human Genetics — Methods and Application: Methods for study of genetic principles in man — family study (pedigree analysis, twin study, foster child, co-twin method, cytogenetic method, chromosomal and karyo-type analysis), biochemical methods, immunological methods, D.N.A. technology and recombinant technologies.",
            "9.2 Mendelian genetics in man — family study, single factor, multifactor, lethal, sublethal and polygenic inheritance in man.",
            "9.3 Concept of genetic polymorphism and selection, Mendelian population, Hardy-Weinberg law; causes and changes which bring down frequency — mutation, isolation, migration, selection, inbreeding and genetic drift. Consanguineous and non-consanguineous mating, genetic load, genetic effect of consanguineous and cousin marriages.",
            "9.4 Chromosomes and chromosomal aberrations in man, methodology: (a) Numerical and structural aberrations (disorders); (b) Sex chromosomal aberrations — Klinefelter (XXY), Turner (XO), Super female (XXX), intersex and other syndromic disorders; (c) Autosomal aberrations — Down syndrome, Patau, Edward and Cri-du-chat syndromes; (d) Genetic imprints in human disease, genetic screening, genetic counseling, human DNA profiling, gene mapping and genome study.",
            "9.5 Race and racism, biological basis of morphological variation of non-metric and metric characters. Racial criteria, racial traits in relation to heredity and environment; biological basis of racial classification, racial differentiation and race crossing in man.",
            "9.6 Age, sex and population variation as genetic marker — ABO, Rh blood groups, HLA Hp, transferring, Gm, blood enzymes. Physiological characteristics — Hb level, body fat, pulse rate, respiratory functions and sensory perceptions in different cultural and socio-economic groups.",
            "9.7 Concepts and methods of Ecological Anthropology. Bio-cultural Adaptations — Genetic and Non-genetic factors. Man's physiological responses to environmental stresses: hot desert, cold, high altitude climate.",
            "9.8 Epidemiological Anthropology: Health and disease. Infectious and non-infectious diseases. Nutritional deficiency related diseases.",
            "10. Concept of human growth and development: stages of growth — pre-natal, natal, infant, childhood, adolescence, maturity, senescence. Factors affecting growth and development — genetic, environmental, biochemical, nutritional, cultural and socio-economic. Ageing and senescence. Theories and observations — biological and chronological longevity. Human physique and somatotypes. Methodologies for growth studies.",
            "11.1 Relevance of menarche, menopause and other bio-events to fertility. Fertility patterns and differentials.",
            "11.2 Demographic theories — biological, social and cultural.",
            "11.3 Biological and socio-ecological factors influencing fecundity, fertility, natality and mortality.",
            "12. Applications of Anthropology: Anthropology of sports, Nutritional anthropology, Anthropology in designing of defence and other equipments, Forensic Anthropology, Methods and principles of personal identification and reconstruction, Applied human genetics — Paternity diagnosis, genetic counseling and eugenics, DNA technology in diseases and medicine, serogenetics and cytogenetics in reproductive biology.",
          ]},
        ],
      },
      {
        id: "anthro2",
        title: "Anthropology Paper II",
        meta: "Optional Subject · Paper VII",
        sections: [
          { items: [
            "1.1 Evolution of the Indian Culture and Civilization — Prehistoric (Palaeolithic, Mesolithic, Neolithic and Neolithic-Chalcolithic). Protohistoric (Indus Civilization): Pre-Harappan, Harappan and post-Harappan cultures. Contributions of tribal cultures to Indian civilization.",
            "1.2 Palaeo-anthropological evidences from India with special reference to Siwaliks and Narmada basin (Ramapithecus, Sivapithecus and Narmada Man).",
            "1.3 Ethno-archaeology in India: The concept of ethno-archaeology; Survivals and Parallels among the hunting, foraging, fishing, pastoral and peasant communities including arts and crafts producing communities.",
            "2. Demographic profile of India — Ethnic and linguistic elements in the Indian population and their distribution. Indian population — factors influencing its structure and growth.",
            "3.1 The structure and nature of traditional Indian social system — Varnashram, Purushartha, Karma, Rina and Rebirth.",
            "3.2 Caste system in India — structure and characteristics, Varna and caste, Theories of origin of caste system, Dominant caste, Caste mobility, Future of caste system, Jajmani system, Tribe-caste continuum.",
            "3.3 Sacred Complex and Nature-Man-Spirit Complex.",
            "3.4 Impact of Buddhism, Jainism, Islam and Christianity on Indian society.",
            "4. Emergence and growth of anthropology in India — Contributions of the 18th, 19th and early 20th Century scholar-administrators. Contributions of Indian anthropologists to tribal and caste studies.",
            "5.1 Indian Village: Significance of village study in India; Indian village as a social system; Traditional and changing patterns of settlement and inter-caste relations; Agrarian relations in Indian villages; Impact of globalization on Indian villages.",
            "5.2 Linguistic and religious minorities and their social, political and economic status.",
            "5.3 Indigenous and exogenous processes of socio-cultural change in Indian society: Sanskritization, Westernization, Modernization; Inter-play of little and great traditions; Panchayati raj and social change; Media and social change.",
            "6.1 Tribal situation in India — Bio-genetic variability, linguistic and socio-economic characteristics of tribal populations and their distribution.",
            "6.2 Problems of the tribal Communities — land alienation, poverty, indebtedness, low literacy, poor educational facilities, unemployment, underemployment, health and nutrition.",
            "6.3 Developmental projects and their impact on tribal displacement and problems of rehabilitation. Development of forest policy and tribals. Impact of urbanization and industrialization on tribal populations.",
            "7.1 Problems of exploitation and deprivation of Scheduled Castes, Scheduled Tribes and Other Backward Classes. Constitutional safeguards for Scheduled Tribes and Scheduled Castes.",
            "7.2 Social change and contemporary tribal societies: Impact of modern democratic institutions, development programmes and welfare measures on tribals and weaker sections.",
            "7.3 The concept of ethnicity; Ethnic conflicts and political developments; Unrest among tribal communities; Regionalism and demand for autonomy; Pseudo-tribalism; Social change among the tribes during colonial and post-Independent India.",
            "8.1 Impact of Hinduism, Buddhism, Christianity, Islam and other religions on tribal societies.",
            "8.2 Tribe and nation state — a comparative study of tribal communities in India and other countries.",
            "9.1 History of administration of tribal areas, tribal policies, plans, programmes of tribal development and their implementation. The concept of PTGs (Primitive Tribal Groups), their distribution, special programmes for their development. Role of N.G.O.s in tribal development.",
            "9.2 Role of anthropology in tribal and rural development.",
            "9.3 Contributions of anthropology to the understanding of regionalism, communalism, and ethnic and political movements.",
          ]},
        ],
      },
    ],
  },

  /* ---------------- INTERVIEW ---------------- */
  interview: {
    title: "Interview Stage",
    heading: "Beyond Bookish Knowledge",
    traits: [
      { name: "Communication Skills", desc: "Can you articulate your thoughts clearly, concisely and persuasively?" },
      { name: "Interpersonal Skills", desc: "Ability to interact effectively with people from diverse backgrounds." },
      { name: "Leadership Qualities", desc: "Ability to inspire, motivate, take initiative and make sound decisions." },
      { name: "Ethical Values", desc: "Integrity, honesty and a strong moral compass." },
      { name: "Problem-Solving Skills", desc: "Ability to analyse complex situations and develop practical solutions." },
      { name: "Stress Management", desc: "Maintain composure under pressure and handle challenging situations gracefully." },
      { name: "Administrative Aptitude", desc: "Possess the qualities required to manage the responsibilities of public administration." },
    ],
  },
};
